openapi: 3.0.1
info:
   title: fruity
   version: 0.0.1
paths:
   /:
      get:
         responses:
            '200':
               description: desc
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/fruit'
components:
   schemas:
      fruit:
        title: fruit
        additionalProperties: false
        properties:
          fruitId:
            type: string
            description: The unique ID of the fruit
          body:
            type: object
            description: |
              The raw event payload that will be different based on the event.
            oneOf:
              - $ref: '#/components/schemas/apple'
              - $ref: '#/components/schemas/banana'
      apple:
         title: apple
         type: object
         properties:
            kind:
               type: string
      banana:
         title: banana
         type: object
         properties:
            count:
               type: number